spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: noreply@blackseatechnology.com
        password: tavn kmce vuvf gvzo
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
              connectiontimeout: 5000
              timeout: 5000
              writetimeout: 5000
#Swagger-UI documentation
springdoc:
    api-docs:
        path: /mailing-docs
    swagger-ui:
        path: /mailing-doc.html    
